# Generated by Django 4.2.3 on 2023-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Senator', max_length=100),
        ),
    ]
