# Generated by Django 4.2.3 on 2023-08-10 14:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
    ]
